// Copyright (c) 2014 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.

package org.cef.input;

import org.cef.misc.EventFlags;

/**
 * Keyboard event information used for direct key event injection via
 * {@code CefBrowser.sendCefKeyEvent}.
 */
public class CefKeyEvent {
    public static final int KEYEVENT_RAWKEYDOWN = 0;
    public static final int KEYEVENT_KEYDOWN = 1;
    public static final int KEYEVENT_KEYUP = 2;
    public static final int KEYEVENT_CHAR = 3;

    /**
     * Event type. One of {@code KEYEVENT_*}.
     */
    public int type = KEYEVENT_RAWKEYDOWN;

    /**
     * Bit flags from {@link EventFlags}.
     */
    public int modifiers = 0;

    /**
     * Windows virtual key code (DOM-compatible key code).
     */
    public int windows_key_code = 0;

    /**
     * Platform-specific native key code.
     */
    public int native_key_code = 0;

    /**
     * True for system key events (mainly meaningful on Windows).
     */
    public boolean is_system_key = false;

    /**
     * The character generated by the keystroke.
     */
    public char character = 0;

    /**
     * Same as {@code character} but unmodified by concurrently-held modifiers
     * (except shift).
     */
    public char unmodified_character = 0;

    /**
     * Optional hardware scan code. On Windows this can be used to infer missing
     * values when {@code windows_key_code} and/or {@code native_key_code} are
     * zero.
     */
    public long scan_code = 0;

    public CefKeyEvent() {}

    public CefKeyEvent(int type, int modifiers, int windows_key_code, int native_key_code,
            boolean is_system_key, char character, char unmodified_character) {
        this(type, modifiers, windows_key_code, native_key_code, is_system_key, character,
                unmodified_character, 0);
    }

    public CefKeyEvent(int type, int modifiers, int windows_key_code, int native_key_code,
            boolean is_system_key, char character, char unmodified_character, long scan_code) {
        this.type = type;
        this.modifiers = modifiers;
        this.windows_key_code = windows_key_code;
        this.native_key_code = native_key_code;
        this.is_system_key = is_system_key;
        this.character = character;
        this.unmodified_character = unmodified_character;
        this.scan_code = scan_code;
    }

    /**
     * Build the Windows lParam-style native key code used by CEF key events.
     */
    public static int buildWindowsNativeKeyCode(long scanCode, boolean extended, boolean keyUp) {
        int nativeCode = (((int) scanCode) << 16) | 1;
        if (extended) {
            nativeCode |= 1 << 24;
        }
        if (keyUp) {
            nativeCode |= 0xC0000000;
        }
        return nativeCode;
    }

    @Override
    public String toString() {
        return "CefKeyEvent[type=" + type + ", modifiers=" + modifiers + ", windows_key_code="
                + windows_key_code + ", native_key_code=" + native_key_code
                + ", is_system_key=" + is_system_key + ", character=" + character
                + ", unmodified_character=" + unmodified_character + ", scan_code=" + scan_code
                + "]";
    }
}
